import { Box, styled } from '@mui/material';

// GitHub .markdown-body 的排版规则，用 MUI palette 取色以跟随明暗模式。
// 编辑器（Milkdown ProseMirror DOM）与 react-markdown 输出共用同一套。
export const MarkdownBody = styled(Box)(({ theme }) => {
  const p = theme.vars!.palette;
  return {
    fontSize: 15,
    lineHeight: 1.65,
    wordWrap: 'break-word',
    color: p.text.primary,
    '& > *:first-of-type': { marginTop: 0 },
    '& > *:last-child': { marginBottom: 0 },
    '& p, & blockquote, & ul, & ol, & dl, & table, & pre': { marginTop: 0, marginBottom: 14 },
    '& h1, & h2, & h3, & h4, & h5, & h6': { marginTop: 22, marginBottom: 14, fontWeight: 600, lineHeight: 1.25 },
    '& h1': { fontSize: '1.8em', paddingBottom: '.3em', borderBottom: `1px solid ${p.divider}` },
    '& h2': { fontSize: '1.45em', paddingBottom: '.3em', borderBottom: `1px solid ${p.divider}` },
    '& h3': { fontSize: '1.2em' },
    '& h4': { fontSize: '1.05em' },
    '& a': { color: p.primary.main, textDecoration: 'none', '&:hover': { textDecoration: 'underline' } },
    '& ul, & ol': { paddingLeft: '2em' },
    '& li + li': { marginTop: 4 },
    '& li.task-list-item, & li[data-item-type="task"]': { listStyle: 'none', marginLeft: '-1.5em' },
    '& li input[type=checkbox]': { marginRight: 8, verticalAlign: 'middle' },
    '& blockquote': {
      margin: '0 0 14px',
      padding: '0 1em',
      color: p.text.secondary,
      borderLeft: `4px solid ${p.divider}`,
    },
    '& code': {
      fontFamily: '"JetBrains Mono", "Fira Code", Menlo, Consolas, monospace',
      fontSize: '85%',
      padding: '.2em .4em',
      borderRadius: 6,
      backgroundColor: `rgba(${p.text.primaryChannel} / 0.08)`,
    },
    '& pre': {
      padding: 16,
      overflow: 'auto',
      borderRadius: 8,
      backgroundColor: `rgba(${p.text.primaryChannel} / 0.05)`,
      border: `1px solid ${p.divider}`,
      fontSize: '85%',
      lineHeight: 1.5,
      '& code': { padding: 0, background: 'none', fontSize: '100%', whiteSpace: 'pre' },
    },
    '& table': {
      display: 'block',
      width: 'max-content',
      maxWidth: '100%',
      overflow: 'auto',
      borderCollapse: 'collapse',
      borderSpacing: 0,
      '& th, & td': { padding: '6px 13px', border: `1px solid ${p.divider}` },
      '& th': { fontWeight: 600, backgroundColor: `rgba(${p.text.primaryChannel} / 0.04)` },
      '& tr:nth-of-type(2n)': { backgroundColor: `rgba(${p.text.primaryChannel} / 0.02)` },
    },
    '& img': { maxWidth: '100%', boxSizing: 'content-box' },
    '& hr': { height: 2, border: 0, margin: '24px 0', backgroundColor: p.divider },
    '& del': { opacity: 0.7 },
    '& .bosun-mermaid svg': { maxWidth: '100%', height: 'auto' },
    '& .bosun-mermaid-error': { color: p.error.main },
    // highlight.js token 配色（精简版 github / github-dark）
    '& .hljs-comment, & .hljs-quote': { color: p.text.secondary, fontStyle: 'italic' },
    '& .hljs-keyword, & .hljs-selector-tag, & .hljs-meta': { color: 'var(--md-kw)' },
    '& .hljs-string, & .hljs-attr, & .hljs-regexp, & .hljs-addition': { color: 'var(--md-str)' },
    '& .hljs-number, & .hljs-literal, & .hljs-built_in, & .hljs-symbol': { color: 'var(--md-num)' },
    '& .hljs-title, & .hljs-function, & .hljs-section, & .hljs-name': { color: 'var(--md-fn)' },
    '& .hljs-type, & .hljs-class, & .hljs-variable, & .hljs-template-variable': { color: 'var(--md-type)' },
    '& .hljs-deletion': { color: p.error.main },
    '--md-fg': p.text.primary,
    '--md-muted': p.text.secondary,
    '--md-border': p.divider,
    '--md-sel': `rgba(${p.primary.mainChannel} / 0.18)`,
    '--md-line': `rgba(${p.text.primaryChannel} / 0.04)`,
    '--md-tooltip-bg': p.background.paper,
    '--md-kw': '#cf222e',
    '--md-str': '#0a3069',
    '--md-num': '#0550ae',
    '--md-fn': '#8250df',
    '--md-type': '#953800',
    ...theme.applyStyles('dark', {
      '--md-kw': '#ff7b72',
      '--md-str': '#a5d6ff',
      '--md-num': '#79c0ff',
      '--md-fn': '#d2a8ff',
      '--md-type': '#ffa657',
    }),
  };
});
